app/auth.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from .models import Users
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from sqlalchemy import or_
from . import db

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    return render_template('login.html')

@auth.route('/login', methods = ['POST'] )
def login_post():
    login = request.form.get('login')
    password = request.form.get('password')

    user = Users.query.filter_by(nickname=login).first()

    #check_password_hash(user.password, password)
    if not user or not check_password_hash(user.password, password):
        flash('Niepoprawne dane!')
        return redirect(url_for('auth.login'))

    login_user(user)
    return redirect(url_for('main.dashboard'))


@auth.route('/sign_up')
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    return render_template('sign_up.html')


@auth.route('/sign_up', methods=['POST'])
def sign_up_post():
    email = request.form.get('email')
    login = request.form.get('login')
    password = request.form.get('password')


    user = Users.query.filter_by(email=email).first()
    user2 = Users.query.filter_by(nickname=login).first()

    if user:
        flash('Email address already exists')
        return redirect(url_for('auth.sign_up'))
    
    if user2:
        flash('Login already exists')
        return redirect(url_for('auth.sign_up'))




    new_user = Users(email=email, nickname=login, password=generate_password_hash(password, method='sha256'), points=0)

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    user = Users.query.filter_by(nickname=login).first()
    login_user(user)

    return redirect(url_for('main.entry'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash
from . import db
from .models import Users,Items,User_inventory,Form_questions, User_tasks, Tasks
from flask_login import current_user
import random


main = Blueprint('main',__name__)

@main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    #pat = Users.query.filter_by(nickname='patryk').first()
    #print(pat.nickname)
   # pat = User_inventory.query.filter_by(item_id=1).first()
    #print(pat.item_id,pat.login_id)

    return render_template('index.html')



@main.route('/dashboard')
def dashboard():
    if current_user.is_authenticated:
        items_list = current_user.login_id # User_inventory.query.filter_by(login_id=current_user.login_id).first() 
        items_list = list()
        tasks_list = list()
        item_shop  = list()
        completed = list()
        # some sphagetti code to show user's items
        for i in User_inventory.query.filter_by(login_id=current_user.login_id).all():
            items_list.append(Items.query.filter_by(item_id=i.item_id).first())

        for i in User_tasks.query.filter_by(login_id=current_user.login_id).all():
            tasks_list.append(Tasks.query.filter_by(task_id=i.task_id).first())
            completed.append(i.completed)

        exclude = list()
        for i in items_list:
            exclude.append(i.item_id)
        exclude = tuple(exclude)

        item_shop = Items.query.filter(~Items.item_id.in_(exclude)).all()


        top5 = Users.query.order_by(Users.points.desc()).limit(5).all()

        return render_template('dashboard.html',items_list=items_list,tasks_list=tasks_list,item_shop=item_shop, top5=top5, completed=completed)
    else:
        return redirect(url_for('auth.login'))


@main.route('/dashboard', methods=['POST'])
def task_update():
    done = request.form.get('done')
    if done:
        res = User_tasks.query.filter((User_tasks.task_id == done) & (User_tasks.login_id == current_user.login_id)).first()
        
        if res.completed == 0:
            task_info = Tasks.query.filter(Tasks.task_id==done).first()
            current_user.points = current_user.points + task_info.points * res.significance
        
        if res.completed == 1:
            flash('Już wykonałeś dzisiaj te zadanie!')
            
        res.completed = 1

        db.session.commit()
        return redirect(url_for('main.dashboard'))

        
    deletion = request.form.get('deletion')
    if deletion:
        rem = User_tasks.query.filter((User_tasks.task_id == deletion) & (User_tasks.login_id == current_user.login_id))
        rem.delete()
        db.session.commit()
        return redirect(url_for('main.dashboard'))


    transaction = request.form.get('transaction')
    if transaction:
        #sprawdz czy ma pieniadze
        koszt = Items.query.filter(Items.item_id==transaction).first().cost
        if current_user.points >= koszt:
            current_user.points=current_user.points-koszt
            new_item = User_inventory(login_id=current_user.login_id,item_id=int(transaction))

            db.session.add(new_item)
            db.session.commit()

            return redirect(url_for('main.dashboard'))

        return f'Nie stać Cię na ten przedmiot!'



@main.route('/entry')
def entry():
    #test entry sprawdza czy nie ma czasem juz wypelnionej ankiety
    test_entry = User_tasks.query.filter_by(login_id=current_user.login_id).first()
    if test_entry:
        return redirect(url_for('main.dashboard'))


    def simple_random():
        return random.sample(Form_questions.query.all(),k=5)

    obj = simple_random()

    session['question_id'] = [(i.task_id,i.negative) for i in obj]

    return render_template('entry.html', start=obj)


@main.route('/entry', methods=['POST'])
def entry_post():
    survey = [request.form.get('survey'+str(i)) for i in range(0,5)]
    survey = [float(x) if x is not None else 0 for x in survey]

    option = session['question_id']
    counter = 0
    final = list()
    for i in option:
        if i[1]==1:
            survey[counter] = survey[counter]* (-1)
        if survey[counter]>0:
            final.append((i[0],survey[counter]))
        counter = counter+1
    


    for j in final:
        new_task = User_tasks(login_id=current_user.login_id,task_id=j[0],significance=j[1],completed=0)
        db.session.add(new_task)


    db.session.commit()


    return redirect(url_for('main.dashboard'))


@main.route('/all_tasks')
def all_tasks():
    if current_user.is_authenticated:
        user_tasks = User_tasks.query.filter_by(login_id=current_user.login_id).all()
        
        exclude = list()
        for i in user_tasks:
            exclude.append(i.task_id)
        exclude = tuple(exclude)

        res = Tasks.query.filter(~Tasks.task_id.in_(exclude)).all()

        return render_template('all_tasks.html', left_tasks=res)
    else:
        return redirect(url_for('auth.login'))

@main.route('/all_tasks', methods=['POST'] )
def add_task():
    a = request.form.get('tasks')

    new_task = User_tasks(login_id=current_user.login_id,task_id=int(a),significance=1,completed=0)
    db.session.add(new_task)
    db.session.commit()
    return redirect(url_for('main.all_tasks'))


@main.route('/reset_blabla')
def reset():
    if current_user.is_authenticated:
        if(current_user.nickname =='patryk'):
            reset_tasks = User_tasks.query.filter_by(completed='1').all()
            if reset_tasks:
                for i in reset_tasks:
                    i.completed = 0
                db.session.commit()

    return f'xd: {reset_tasks}'

app/templates/all_tasks.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block css %}{% endblock %}

{% block body %}

<h2><a href="{{ url_for('main.dashboard') }}">Dashboard</a></h2>

<form method="POST" action="{{ url_for('main.add_task') }}">
    <table class="table" border="1" cellpadding="10px" cellspacing="5px">
    {% for item in left_tasks %}
        <tr>
            <td> {{ item.name }} </td>
            <td><button name="tasks" type="submit" value={{item.task_id}}>dodaj</button> </td>
        </tr>
        {% endfor %}
    </table>
</form>

{% endblock %}

app/templates/base.html
<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    {% block css %}{% endblock %}

</head>

<body>
    {% block body %}{% endblock %}
</body>

</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dashboard.css') }}">
{% endblock %}

{% block body %}
<div class=container>
    <div class=info>
        <h1>Witaj {{ current_user.nickname }}, masz {{ current_user.points }} punktów</h1>
    </div>

    <div class=clear>
        <a href="{{ url_for('main.all_tasks') }}">Wszystkie zadania!</a>
        <a href="{{ url_for('auth.logout') }}">Wyloguj się</a>
    </div>
    <div class=tholder>
        <h3>Twoja zadania!</h3>
        {% if tasks_list is defined and tasks_list|length %}
        <form method="POST" action="{{ url_for('main.task_update') }}">
            <table class="table" border="1" cellpadding="10px" cellspacing="5px">
                {% for item in tasks_list %}
                {% if completed[loop.index0] is sameas true %}
                {% set disabled = 'disabled' %}
                <tr class='completed'>
                    {% else %}
                <tr>
                    {% endif %}
                    <td>{{ item.name }} </td>
                    <td><button name="done" type="submit" value={{item.task_id}}>Zrobione!</button></td>
                    <td><button name="deletion" type="submit" class="close" aria-label="Close" value={{item.task_id}}
                            {{ disabled }}>
                            <span aria-hidden="true">&times;</span></button> </td>
                </tr>

                {% endfor %}
            </table>
        </form>
        {% else %}
        <table class="table" border="1" cellpadding="10px" cellspacing="5px">
            <tr>
                <td>
                    Nie masz żadnych zadań, <a href="{{ url_for('main.all_tasks') }}">kliknij tutaj</a>
                    żeby jakieś dodać!
                </td>
            </tr>
        </table>
        {% endif %}
    </div>

    <div class=inventory>
        <h3>Ekwipunek</h3>
        {% if items_list is defined and items_list|length %}
        <table class="table" border="1" cellpadding="10px" cellspacing="5px">
            {% for item in items_list %}
            <tr>
                <td><img src="{{url_for('static', filename=item.img_source)}}" alt={{ item.img_source }} width="30" height="30"> </td>
                <td>{{ item.name }}</td>
            </tr>

            {% endfor %}
        </table>
        {% else %}
        <table class="table" border="1" cellpadding="10px" cellspacing="5px">
            <tr>
                <td>
                    Nie masz żadnych rzeczy, jak coś w sklepie!
                </td>
            </tr>
        </table>
        {% endif %}
    </div>


    <div class=shop>
        <h3>Sklep</h3>
        {% if item_shop is defined and item_shop|length %}
        <form method="POST" action="{{ url_for('main.task_update') }}">
            <table class="table" border="1" cellpadding="10px" cellspacing="5px">
                {% for item in item_shop %}
                <tr>
                    <td><img src="{{url_for('static', filename=item.img_source)}}" alt={{ item.img_source }} width="30" height="30"> </td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.cost }}</td>
                    <td><button name="transaction" type="submit" value={{item.item_id}}>kup</button></td>
                </tr>

                {% endfor %}
            </table>
        </form>

        {% else %}
        <table class="table" border="1" cellpadding="10px" cellspacing="5px">
            <tr>
                <td>
                    Nie ma nic w sklepie... Chyba wszystko wykupiłeś/aś!
                </td>
            </tr>
        </table>
        {% endif %}

    </div>



    <div class=shop>
        <h3>TOP5</h3>
        <table class="table" border="1" cellpadding="10px" cellspacing="5px">
            {% for item in top5 %}
            <tr>
                <td>{{ item.nickname }}</td>
                <td>{{ item.points }}</td>
            </tr>

            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

app/templates/entry.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block css %}
<style>
    .btn-info.active {
        background-color: limegreen;
    }

    .btn_red.active {
        background-color: red;
    }
</style>

{% endblock %}




{% block body %}
<div class="container center mt-sm-3" class="mx-auto">

<h4>Prosimy o wypełnienie krótkiego formularza w celu dopasowania preferencji!</h4>


<form method="POST" action="{{ url_for('main.entry_post') }}">

{% for item in start %}
    <div class='border'>
    <h5>{{ item.question }}</h5>

        <label class="radio-inline">
            <input type="radio" name="survey{{ loop.index0 }}" id="Radios1" value="-1">
            Tak
        </label>
        <label class="radio-inline">
            <input type="radio" name="survey{{ loop.index0 }}" id="Radios2" value="-0.5">
            Raczej tak
        </label>
        <label class="radio-inline">
            <input type="radio" name="survey{{ loop.index0 }}" id="Radios3" value="0">
            Nie chcę odpowiadać/nie wiem
        </label>
        <label class="radio-inline">
            <input type="radio" name="survey{{ loop.index0 }}" id="Radios4" value="0.5">
            Raczej nie
        </label>
        <label class="radio-inline">
            <input type="radio" name="survey{{ loop.index0 }}" id="Radios5" value="1">
            Nie
        </label>
    </div>

{% endfor %}
<div class='float-right'><button type="submit" class="btn btn-primary">Submit</button></div>
</form>

{{ option }}
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block css %}{% endblock %}

{% block body %}
<div  class='container col-md-8 mx-auto align-middle'>
<h1>Hey, witam bardzo SKROMNIE w habitsapp!</h1>
<h2><a href="{{ url_for('auth.login') }}">Zaloguj się!</a></h2>
<h2><a href="{{ url_for('auth.sign_up') }}">Zarejestruj się!</a> </h2>

</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block css %}
<style>
  .tight{
    margin-top: 50px;
    width: 200px;
    background-color: rgb(250, 198, 198);
  }
</style>
{% endblock %}

{% block body %}
<div class="container tight">
  <form method="POST" action="{{ url_for('auth.login_post') }}">
    <div class="form-group">
      Login
      <input type="login" class="form-control" name="login" id="login" placeholder="login">
      Hasło
      <input type="password" class="form-control" name="password" id="password" placeholder="password">
    </div>
    <center><button type="submit" class="btn btn-primary">Submit</button></center>
    <br><br>
  </form>
</div>
{% endblock %}

app/templates/sign_up.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}

{% block css %}
<style>
  .tight{
    margin-top: 50px;
    width: 200px;
    background-color: rgb(250, 198, 198);
  }
</style>
{% endblock %}

{% block body %}
<div class="container tight">
  <form method="POST" action="{{ url_for('auth.sign_up_post') }}">
    <div class="form-group">
      E-mail
      <input type="email" class="form-control" name="email" id="email" placeholder="email">
      Login
      <input type="login" class="form-control" name="login" id="login" placeholder="login">
      Hasło
      <input type="password" class="form-control" name="password" id="password" placeholder="password">
    </div>
    <br>
    <center><button type="submit center" class="btn btn-primary">Submit</button></center>
    <br>
  </form>
</div>
{% endblock %}